export default [
    {
        id: 0 ,
        img: "/lipstick1.png" ,
        name:"wild Slik finish Lipstick" ,
        price:41.0,
        category:['lipsticks','makeup'],
        sale: false ,
    },
    {
        id: 1 ,
        img: "/lipstick2.png" ,
        name:"wild Slik finish Lipstick" ,
        price:41.0,
        category:['lipsticks'],
        sale: false ,
    },
    {
        id: 2 ,
        img: "/lipstick3.png" ,
        name:"wild Slik finish Lipstick" ,
        price:41.0,
        category:['lipsticks'],
        sale: true ,
    },
    {
        id: 3 ,
        img: "/lipstick4.png" ,
        name:"wild Slik finish Lipstick" ,
        price:41.0,
        category:['lipsticks','makeup'],
        sale: false ,
    },
    {
        id: 4 ,
        img: "/lipstick5.png" ,
        name:"wild Slik finish Lipstick" ,
        price:41.0,
        category:['lipsticks'],
        sale: true ,
    },
    {
        id: 5 ,
        img: "/lipstick6.png" ,
        name:"wild Slik finish Lipstick" ,
        price:41.0,
        category:['lipsticks'],
        sale: false ,
    },
    {
        id: 6 ,
        img: "/lipstick7.png" ,
        name:"wild Slik finish Lipstick" ,
        price:41.0,
        category:['lipsticks'],
        sale: true ,
    },
    {
        id: 7 ,
        img: "/lipstick8.png" ,
        name:"wild Slik finish Lipstick" ,
        price:41.0,
        category:['lipsticks'],
        sale: true ,
    },
    {
        id: 8 ,
        img: "/lipstick9.png" ,
        name:"wild Slik finish Lipstick" ,
        price:41.0,
        category:['lipsticks','makeup'],
        sale: true ,
    },
    {
        id: 9 ,
        img: "/nailpolish1.png" ,
        name:"Nail Polish 001" ,
        price:35.0,
        category:['nailpolish'],
        sale: false ,
    },
    {
        id: 10 ,
        img: "/nailpolish2.png" ,
        name:"Nail Polish 002" ,
        price:35.0,
        category:['nailpolish'],
        sale: false ,
    },
    {
        id: 11 ,
        img: "/nailpolish3.png" ,
        name:"Nail Polish 003" ,
        price:35.0,
        category:['nailpolish'],
        sale: true ,
    },
    {
        id: 12 ,
        img: "/nailpolish4.png" ,
        name:"Nail Polish 004" ,
        price:35.0,
        category:['nailpolish'],
        sale: false ,
    },
    {
        id: 13 ,
        img: "/nailpolish5.png" ,
        name:"Nail Polish 005" ,
        price:35.0,
        category:['nailpolish'],
        sale: false ,
    },
    {
        id: 14 ,
        img: "/nailpolish6.png" ,
        name:"Nail Polish 006" ,
        price:35.0,
        category:['nailpolish'],
        sale: true ,
    },
    {
        id: 15 ,
        img: "/nailpolish7.png" ,
        name:"Nail Polish 007" ,
        price:35.0,
        category:['nailpolish'],
        sale: false ,
    },
    {
        id: 16 ,
        img: "/nailpolish8.png" ,
        name:"Nail Polish 008" ,
        price:35.0,
        category:['nailpolish'],
        sale: true ,
    },
    {
        id: 17 ,
        img: "/nailpolish9.png" ,
        name:"Nail Polish 009" ,
        price:35.0,
        category:['nailpolish'],
        sale: false ,
    },
    {
        id: 18 ,
        img: "/nailpolish10.png" ,
        name:"Nail Polish 010" ,
        price:35.0,
        category:['nailpolish'],
        sale: true ,
    },
    {
        id: 19 ,
        img: "/nailpolish11.png" ,
        name:"Nail Polish 011" ,
        price:35.0,
        category:['nailpolish'],
        sale: false ,
    },
    {
        id: 20 ,
        img: "/nailpolish12.png" ,
        name:"Nail Polish 012" ,
        price:35.0,
        category:['nailpolish'],
        sale: false ,
    },
    {
        id: 21 ,
        img: "/nailpolish13.png" ,
        name:"Nail Polish 013" ,
        price:35.0,
        category:['nailpolish'],
        sale: false ,
    },
    {
        id: 22 ,
        img: "/lipglose1.png" ,
        name:"Lip Glose #011" ,
        price:135.0,
        category:['lipglose', 'makeup'],
        sale: false ,
    },
    {
        id: 23 ,
        img: "/lipglose2.png" ,
        name:"Lip Glose #012" ,
        price:135.0,
        category:['lipglose'],
        sale: false ,
    },
    {
        id: 24 ,
        img: "/lipglose3.png" ,
        name:"Lip Glose #013" ,
        price:135.0,
        category:['lipglose'],
        sale: false ,
    },
    {
        id: 25 ,
        img: "/lipglose4.png" ,
        name:"Lip Glose #014" ,
        price:135.0,
        category:['lipglose','makeup'],
        sale: true ,
    },
    {
        id: 26 ,
        img: "/lipglose5.png" ,
        name:"Lip Glose #015" ,
        price:135.0,
        category:['lipglose'],
        sale: false ,
    },
    {
        id: 27 ,
        img: "/lipglose6.png" ,
        name:"Lip Glose #016" ,
        price:135.0,
        category:['lipglose'],
        sale: false ,
    },
    {
        id: 28 ,
        img: "/lipglose7.png" ,
        name:"Lip Glose #016" ,
        price:135.0,
        category:['lipglose'],
        sale: false ,
    },
    {
        id: 29 ,
        img: "/lipglose8.png" ,
        name:"Lip Glose #017" ,
        price:135.0,
        category:['lipglose'],
        sale: true ,
    },
    {
        id: 30 ,
        img: "/blender1.png" ,
        name:"Makeup Blender" ,
        price:15.0,
        category:['makeup'],
        sale: true ,
    },
    {
        id: 31 ,
        img: "/blender2.png" ,
        name:"Makeup Blender" ,
        price:25.0,
        category:['makeup'],
        sale: true ,
    },
    {
        id: 32 ,
        img: "/blender3.png" ,
        name:"Makeup Blender" ,
        price:25.0,
        category:['makeup'],
        sale: true ,
    },
    {
        id: 33 ,
        img: "/blush1.png" ,
        name:"Blusher #201" ,
        price:85.0,
        category:['makeup'],
        sale: false ,
    },
    {
        id: 34 ,
        img: "/blush2.png" ,
        name:"Blusher #202" ,
        price:85.0,
        category:['makeup'],
        sale: false ,
    },
    {
        id: 35 ,
        img: "/blush3.png" ,
        name:"Blusher #203" ,
        price:85.0,
        category:['makeup'],
        sale: false ,
    },
    {
        id: 36 ,
        img: "/blush4.png" ,
        name:"Blusher #204" ,
        price:85.0,
        category:['makeup'],
        sale: true ,
    },
    {
        id: 37 ,
        img: "/blush5.png" ,
        name:"Blusher #205" ,
        price:85.0,
        category:['makeup'],
        sale: false ,
    },
    {
        id: 38 ,
        img: "/blush6.png" ,
        name:"Blusher #206" ,
        price:85.0,
        category:['makeup'],
        sale: true ,
    },
    {
        id: 39 ,
        img: "/blush7.png" ,
        name:"Blusher #207" ,
        price:85.0,
        category:['makeup'],
        sale: false ,
    },
    {
        id: 40 ,
        img: "/compact_powder.png" ,
        name:"Compact Powder" ,
        price:325.0,
        category:['makeup'],
        sale: false ,
    },
    {
        id: 41 ,
        img: "/concellor.png" ,
        name:"Concellor" ,
        price:70.0,
        category:['makeup'],
        sale: false ,
    },
    {
        id: 42 ,
        img: "/eyeliner.png" ,
        name:"EYE Liner" ,
        price:75.0,
        category:['makeup'],
        sale: false ,
    },
    {
        id: 43 ,
        img: "/gel_eyeliner.png" ,
        name:"Gel EYE Liner" ,
        price:100.0,
        category:['makeup'],
        sale: false ,
    },
    {
        id: 44 ,
        img: "/eyeshadow1.png" ,
        name:"Eye Shadow Palate 01" ,
        price:200.0,
        category:['makeup'],
        sale: false ,
    },
    {
        id: 45 ,
        img: "/eyeshadow2.png" ,
        name:"Eye Shadow Palate 02" ,
        price:220.0,
        category:['makeup'],
        sale: false ,
    },
    {
        id: 46 ,
        img: "/eyeshadow3.png" ,
        name:"Eye Shadow Palate 03" ,
        price:150.0,
        category:['makeup'],
        sale: true ,
    },
    {
        id: 47 ,
        img: "/eyeshadow4.png" ,
        name:"Eye Shadow Palate 04" ,
        price:175.0,
        category:['makeup'],
        sale: false ,
    },
    {
        id: 48 ,
        img: "/foundation1.png" ,
        name:"Foundation bg#01" ,
        price:300.0,
        category:['makeup'],
        sale: false ,
    },
    {
        id: 49 ,
        img: "/foundation2.png" ,
        name:"Foundation bg#02" ,
        price:300.0,
        category:['makeup'],
        sale: false ,
    },
    {
        id: 50 ,
        img: "/foundation3.png" ,
        name:"Foundation bg#03" ,
        price:300.0,
        category:['makeup'],
        sale: true ,
    },
    {
        id: 51 ,
        img: "/foundation4.png" ,
        name:"Foundation bg#04" ,
        price:300.0,
        category:['makeup'],
        sale: false ,
    },
    {
        id: 52 ,
        img: "/foundation5.png" ,
        name:"Foundation bg#05" ,
        price:300.0,
        category:['makeup'],
        sale: true ,
    },
    {
        id: 53 ,
        img: "/foundation6.png" ,
        name:"Foundation bg#06" ,
        price:300.0,
        category:['makeup'],
        sale: false ,
    },
    {
        id: 54 ,
        img: "/highlighter1.png" ,
        name:"Highligher #0S1" ,
        price:125.0,
        category:['makeup'],
        sale: false ,
    },
    {
        id: 55 ,
        img: "/highlighter2.png" ,
        name:"Highligher #0S2" ,
        price:125.0,
        category:['makeup'],
        sale: false ,
    },
    {
        id: 56 ,
        img: "/highlighter3.png" ,
        name:"Highligher #0S3" ,
        price:125.0,
        category:['makeup'],
        sale: true ,
    },
    {
        id: 57 ,
        img: "/highlighter4.png" ,
        name:"Highligher #0S4" ,
        price:125.0,
        category:['makeup'],
        sale: false ,
    },
    {
        id: 58 ,
        img: "/mascara.png" ,
        name:"EYE Lashes Mascara" ,
        price:115.0,
        category:['makeup'],
        sale: false ,
    },
    
]